### ISSUE TITLE
Accelerad Addition?

### ISSUE THREAD

**Issue by twanito** [GroundhogLighting/Groundhog#34]
Hi,

I've just read through some of the doc and looked at the radiance binaries used and had one question: is it possible to use accelerad binaries with this plugin? I've not had a chance to play with all of this yet but thought I'd ask before giving it a go.

Thanks!

ps: this is accelerad (http://web.mit.edu/SustainableDesignLab/projects/Accelerad/)

**Comment by germolinal** [comment]
Hello Twanito, 

I believe it is possible to "hack" this in order to use Accelerad, but I have not attempted it.

When I tried accelerad (a while ago) I had some issues, and it not work well for me. Also I have no permission to actually distribute it. However, if you want to try, let me know and I will tell you how to do it.

best

**Comment by germolinal** [comment]
Hello twanito, 

I believe that if you replace the Radiance's RTRACE and RCONTRIB programs by their Accelerad analogs  in your Groundhog installation, this should work!

Did you make any attempt?
